{{- if .Values.confimaps.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "web-kubectl.fullname" . }}
  labels:
    {{- include "web-kubectl.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.envAnnotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
data:
  {{- toYaml .Values.confimaps.configMapData | nindent 2 }}
{{- end }}